- name: steam-workshop-upload
  uses: weilbyte/steam-workshop-upload@v1 
  with: 
    appid: 312520 # 雨世界的ID
    itemid: 3072912119 # 模组翻译的ID
    path: 'Rainworld-ModTranslation' # 模组的根目录
    env: 
      STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }} # Your Steam username 
      STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }} # Your Steam password 
      STEAM_TFASEED: ${{ secrets.STEAM_TFASEED }} # Your Steam Guard 2FA shared secret (Optional)


