on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  byd:
    runs-on: ubuntu-latest
    steps:
    # sets up the steamcmd command alias
    - uses: RageAgainstThePixel/setup-steamcmd@v1
    # uploads a build or workshop item to steam
    - uses: RageAgainstThePixel/upload-steam@v1
      id: upload
      with:
        username: ${{ secrets.STEAM_USERNAME }}
        password: ${{ secrets.STEAM_PASSWORD }}
        shared_secret: ${{ secrets.STEAM_TFASEED }}
        app_id: 312520
        workshop_item_id: 3072912119
        depot_file_exclusions: |
          bin/tools*
          *.meta
      # use outputs
    - run: |
        manifest="${{ steps.upload.outputs.manifest }}"
        cat $manifest
      shell: bash
